### ISSUE TITLE
Introducing a new paper which will be published in NeurIPS 2022

### ISSUE THREAD

**Issue by dongmean** [baifanxxx/awesome-active-learning#13]
First of all, thank you very much for providing an awesome github repo for AL survey :)

I want to introduce a new AL work, which will be published in NeurIPS 2022

`Paper & Code for the new paper`
- Meta-Query-Net: Resolving Purity-Informativeness Dilemma in Open-set Active Learning [[pdf](https://arxiv.org/pdf/2210.07805.pdf)] [[code](https://github.com/kaist-dmlab/MQNet)]

It would be a great honor if you include or mention our work in your repo :)
Thanks again for your great work!

**Comment by baifanxxx** [comment]
Thank you for your information.
